load Settings.empresa + '/factura_report.rb'
load Settings.empresa + '/recibo_cuota.rb'
load Settings.empresa + '/extracto_cliente_report.rb'
load Settings.empresa + '/uso_interno_report.rb'
load Settings.empresa + '/transferencia_report.rb'
load Settings.empresa + '/producto_lote_report_xls.rb'
load Settings.empresa + '/consentimiento_cirugia_report.rb'
load Settings.empresa + '/revocacion_cirugia_report.rb'
load Settings.empresa + '/legajo_paciente_report.rb'
load Settings.empresa + '/tratamientos_consultorio_report.rb'
load Settings.empresa + '/receta_report.rb'

require 'movimiento_venta_report.rb'
require 'printer_service.rb'
require 'compra_cuotas_report.rb'
require 'compras_report.rb'
require 'ganancias_report.rb'
require 'inventarios_report.rb'
require 'ventas_report.rb'
require 'retencion_report.rb'
require 'movimiento_caja_report.rb'
require 'producto_recargo_report.rb'
require 'ventas_medio_pago_report.rb'
require 'precios_venta_report.rb'
require 'caja_usuario_report.rb'
require 'final_caja_report.rb'
require 'producto_lote_report.rb'
require 'operacion_report.rb'
require 'descuento_report.rb'
require 'evento_report.rb'
